#!/usr/bin/env bash
######################################################################
##  Save periodic snapshots of files for later analysis
######################################################################


                
function take_snapshot {
    DATA_JSON_OUT="${DATA_DIR}${DATA_JSON_OUT_PREFIX}_$(date '+%Y-%m-%d')_data.json"
    echo "Saving "$DATA_JSON_URL" to "$DATA_JSON_OUT
    /usr/bin/curl  -s -o $DATA_JSON_OUT "$DATA_JSON_URL"  2> $LOG_FILE
}  


# Set destination for output files
DATA_DIR="./snapshots/"
LOG_FILE=$DATA_DIR"cron_curl_error.out"

echo -e "\n\n\n   -----   Running snapshot at: $(date)   -----\n"


#--- Take snapshot of GitHub issues ---
DATA_JSON_URL="https://api.github.com/repos/demand-driven-open-data/ddod-intake/issues?state=all&per_page=10000"
DATA_JSON_OUT_PREFIX="ddod_intake_issues"
take_snapshot



#--- Take snapshot of open.fda.gov ---
DATA_JSON_URL="https://open.fda.gov/data.json"
DATA_JSON_OUT_PREFIX="open.fda.gov"
take_snapshot


#--- Take snapshot of data.cdc.gov ---
DATA_JSON_URL="https://data.cdc.gov/data.json"
DATA_JSON_OUT_PREFIX="data.cdc.gov"
take_snapshot


#--- Take snapshot of data.cms.gov ---
DATA_JSON_URL="http://data.cms.gov/data.json"
DATA_JSON_OUT_PREFIX="data.cms.gov"
take_snapshot


#--- Take snapshot of dnav.cms.gov ---
DATA_JSON_URL="https://dnav.cms.gov/api/healthdata"
DATA_JSON_OUT_PREFIX="dnav.cms.gov"
take_snapshot
rename 's/\.json$/\.xml/' $DATA_JSON_OUT    # Accommodate XML file


#--- Take snapshot of HealthData.gov ---
DATA_JSON_URL="http://www.healthdata.gov/data.json"  # Or...  "http://healthdatagov.prod.acquia-sites.com/data.json"
DATA_JSON_OUT_PREFIX="HealthData.gov"
take_snapshot



#--- Take snapshot of data.gov ---
DATA_JSON_URL="http://open.gsa.gov/data.json"
DATA_JSON_OUT_PREFIX="Data.gov"
take_snapshot
